version: '3.8'

services:
  web:
    build: .
    command: ./boot.sh
    volumes:
      - .:/home/parthenopeddit
    ports:
      - 5000:5000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env.mysql

volumes:
  mysql_data: