"""empty message

Revision ID: fd643f1f8937
Revises: 
Create Date: 2020-06-08 17:03:07.668551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd643f1f8937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_name'), 'board', ['name'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=255), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(length=4294000000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_timestamp'), 'content', ['timestamp'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_token',
    sa.Column('token', sa.String(length=1024), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('body', sa.Text(length=4294000000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('replies_to_message_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['replies_to_message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('of_user_id', sa.String(length=255), nullable=False),
    sa.Column('last_opened_on', sa.DateTime(), nullable=True),
    sa.Column('other_user_chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['of_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['other_user_chat_id'], ['users_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commented_content_id', sa.Integer(), nullable=False),
    sa.Column('root_content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commented_content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['root_content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dislikes',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.create_table('group_chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('of_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['of_group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_invite',
    sa.Column('inviter_id', sa.String(length=255), nullable=False),
    sa.Column('invited_id', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['invited_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('inviter_id', 'invited_id', 'group_id')
    )
    op.create_table('group_member',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('last_chat_read', sa.DateTime(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('posted_to_board_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['posted_to_board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_liking', sa.Integer(), nullable=True),
    sa.Column('score_difficulty', sa.Integer(), nullable=True),
    sa.Column('reviewed_course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['reviewed_course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_follows_course',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follows_course')
    op.drop_table('review')
    op.drop_table('post')
    op.drop_table('likes')
    op.drop_table('group_member')
    op.drop_table('group_invite')
    op.drop_table('group_chat')
    op.drop_table('dislikes')
    op.drop_table('comment')
    op.drop_table('users_chat')
    op.drop_table('message')
    op.drop_table('group')
    op.drop_table('device_token')
    op.drop_table('course')
    op.drop_index(op.f('ix_content_timestamp'), table_name='content')
    op.drop_table('content')
    op.drop_table('user')
    op.drop_table('chat')
    op.drop_index(op.f('ix_board_name'), table_name='board')
    op.drop_table('board')
    # ### end Alembic commands ###
